version: '3.7'
services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_db:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_db:/data
volumes:
  redis_db:
  postgres_db:
